### ISSUE TITLE
Display record identifier on the record page

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/data-catalog#2]
Currently, the record identifier is not displayed anywhere and it is available only from the URL of the record

- [x] Display record identifier 

Not sure about the placement, but it should be rather visible on top section of the record page. Maybe breadcrumbs?

Examples: 
- https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE245725
- https://ega-archive.org/datasets/EGAD00001000002

**Comment by vildead** [comment]
more examples:
https://www.synapse.org/Synapse:syn5511429/tables/

Project SynID, DOI, Location .... all these right under the name of the project/dataset/entity

**Comment by neoflex** [comment]
for project, dataset, study, show id below title
show id in search results cards
allow searching based on id

**Comment by vildead** [comment]
implemented in sprint 2024-08
